version: "3"

services:
  wg:
    build: .
    #image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    cap_add:
      - NET_ADMIN
    network_mode: host
    environment:
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME=gowo.tv
      - WGUI_USERNAME=alpha
      - WGUI_PASSWORD=this-unusual-password
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
      - WGUI_DNS=10.13.13.1
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ./db:/app/db
      - /etc/wireguard:/etc/wireguard
